/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.Main;

import com.ridwan.DAO.PetugasDao;
import com.ridwan.dialog.Dialog_update_gudang;
import com.ridwan.dialog.TampilReport;
import com.ridwan.dialog.Trx_Bytgl;
import com.ridwan.dialog.info_gudang;
import com.ridwan.frm.GudangFrm;
import com.ridwan.frm.KategoriFrm;
import com.ridwan.frm.LaporanFrm;
import com.ridwan.frm.OBATFRM;
import com.ridwan.frm.PetugasFrm;
import com.ridwan.frm.TransaksiFrm;
import com.ridwan.frm.loginform;
import com.ridwan.model.PetugasModel;
import com.sun.jmx.snmp.SnmpDataTypeEnums;
import java.awt.GraphicsConfiguration;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ciwong
 */
public class MAIN_MENU extends javax.swing.JFrame {
    
    private OBATFRM obatfrm;
    private boolean mode;
    private TransaksiFrm transaksiFrm;
 
    private MAIN_MENU m;
    
   public JTextField getTxtPengguna(){
        return txt_pengguna;
    }
    
    public void setTxtPengguna(JTextField txtpengguna){
        this.txt_pengguna = txtpengguna;
    }
 public void kasir (){
        btn_petugas.setEnabled(false);
        btn_datagudang.setEnabled(false);
        btn_inputobat.setEnabled(false);
        btn_inputkategori.setEnabled(false);
        
        
    }
    
    public void karyawan (){
        btn_penjualan.setEnabled(false);
        btn_petugas.setEnabled(false);
       
       btn_datagudang.setEnabled(false);
    }
    
    public void gudang(){
        btn_petugas.setEnabled(false);
        
        btn_penjualan.setEnabled(false);
        btn_inputobat.setEnabled(false);
        btn_inputkategori.setEnabled(false);
        btn_laporan.setEnabled(false);
    }
    
    public void admin (){
    }
    

    /**
     * Creates new form MAIN_MENU
     */
    public MAIN_MENU() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        obatfrm = new OBATFRM();;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bnt_logout = new javax.swing.JButton();
        btn_penjualan = new javax.swing.JButton();
        btn_inputobat = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_inputkategori = new javax.swing.JButton();
        btn_petugas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_pengguna = new javax.swing.JTextField();
        btn_Infogudang = new javax.swing.JButton();
        btn_datagudang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bnt_logout.setText("LOGOUT");
        bnt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_logoutActionPerformed(evt);
            }
        });

        btn_penjualan.setText("PENJUALAN");
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });

        btn_inputobat.setText("INPUT OBAT");
        btn_inputobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputobatActionPerformed(evt);
            }
        });

        btn_laporan.setText("LAPORAN");
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });

        btn_inputkategori.setText("INPUT KATEGORI");
        btn_inputkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputkategoriActionPerformed(evt);
            }
        });

        btn_petugas.setText("TAMBAH PETUGAS");
        btn_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_petugasActionPerformed(evt);
            }
        });

        jLabel1.setText("USER LOGIN :");

        txt_pengguna.setEnabled(false);
        txt_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_penggunaActionPerformed(evt);
            }
        });

        btn_Infogudang.setText("INFO GUDANG");
        btn_Infogudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InfogudangActionPerformed(evt);
            }
        });

        btn_datagudang.setText("DATA GUDANG");
        btn_datagudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datagudangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_Infogudang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_datagudang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_inputkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bnt_logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_inputobat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(745, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inputobat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_datagudang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inputkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Infogudang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bnt_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
    TransaksiFrm frm = new TransaksiFrm();
    frm.setVisible(true);
    
   
    
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_inputobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputobatActionPerformed
        OBATFRM obatfrm = new OBATFRM();
        obatfrm.setVisible(true);
    }//GEN-LAST:event_btn_inputobatActionPerformed

    private void btn_inputkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputkategoriActionPerformed
KategoriFrm kategoriFrm = new KategoriFrm();
kategoriFrm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_inputkategoriActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
LaporanFrm frm = new LaporanFrm();
frm.setVisible(true);
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_petugasActionPerformed
PetugasFrm petugasFrm = new PetugasFrm();
petugasFrm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_petugasActionPerformed

    private void txt_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_penggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_penggunaActionPerformed

    private void btn_InfogudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InfogudangActionPerformed
       info_gudang info = new info_gudang();
       info.setVisible(true);
    }//GEN-LAST:event_btn_InfogudangActionPerformed

    private void btn_datagudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datagudangActionPerformed
       GudangFrm frm = new GudangFrm();
       frm.setVisible(true);
    }//GEN-LAST:event_btn_datagudangActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
    }//GEN-LAST:event_formWindowOpened

    private void bnt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_logoutActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_logoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_MENU().setVisible(true);
            }
        });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_logout;
    private javax.swing.JButton btn_Infogudang;
    private javax.swing.JButton btn_datagudang;
    private javax.swing.JButton btn_inputkategori;
    private javax.swing.JButton btn_inputobat;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_petugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_pengguna;
    // End of variables declaration//GEN-END:variables

    
}
