/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.frm;

import com.ridwan.DAO.GudangDao;
import com.ridwan.DAO.KategoriDao;
import com.ridwan.TableModel.TableModelGudang;
import com.ridwan.dialog.Dialog_update_gudang;
import com.ridwan.model.GudangModel;
import com.ridwan.model.KategoriModel;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ciwong
 */
public class GudangFrm extends javax.swing.JFrame implements DocumentListener{

    private GudangModel gm;
    private GudangDao gudangDao = new GudangDao();
    private TableModelGudang tableModelGudang = new TableModelGudang();
    private TableRowSorter rowSorter;
    
    
    public GudangFrm() {
        initComponents();
        setLocationRelativeTo(null);
        tabel_gudang.setModel(tableModelGudang);
        loadData();
        loadGudang();
        rowSorter = new TableRowSorter(tabel_gudang.getModel());
       tabel_gudang.setRowSorter(rowSorter);
      txt_cariobat.getDocument().addDocumentListener(this);
    }
    
    
    private void Saring(){
        String text = txt_cariobat.getText();
        if (text.length()==0){
            rowSorter.setRowFilter(null);
        }else {
           rowSorter.setRowFilter(RowFilter.regexFilter
        (Pattern.compile("(?i).*" + text + ".*", Pattern.CASE_INSENSITIVE|Pattern.DOTALL ).toString()));
        }
    }
    
    
    private void loadData(){
        List<GudangModel> gudangModels = gudangDao.getgudangModels();
        tableModelGudang.setData(gudangModels);
    }
    
    private void loadGudang(){
        List<GudangModel> gudangModels = gudangDao.getgudangModels();
        for (GudangModel g : gudangModels){
            cbo_gudang.addItem(g);
        }
    }
    
    
    private boolean validasiInput(){
        boolean valid = false;
        if (txt_kodegudang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode Gudang Masih Kosong");
        }else if (txt_namagudang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Gudang Masih Kosong");
        }else if (txt_namaobat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Obat Belum Diiisi");
        }else if (txt_jumlahstok.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Stok Obat Belum Diisi");
        }else {
            valid = true;
        }
        return valid;
    }
    
    
    private void resetFrm(){
        txt_kodegudang.setText("");
        txt_namagudang.setText("");
        txt_namaobat.setText("");
        txt_jumlahstok.setText("");
        cbo_gudang.setSelectedIndex(0);
        txt_cariobat.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_kodegudang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_namagudang = new javax.swing.JTextField();
        btn_getcode = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_namaobat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_jumlahstok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_gudang = new javax.swing.JTable();
        txt_cariobat = new javax.swing.JTextField();
        cbo_gudang = new javax.swing.JComboBox();
        btn_carigudang = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_simpan = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORM DATA GUDANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("ID GUDANG : ");

        txt_kodegudang.setEnabled(false);

        jLabel3.setText("NAMA GUDANG :");

        btn_getcode.setText("GET");
        btn_getcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getcodeActionPerformed(evt);
            }
        });

        jLabel5.setText("NAMA OBAT :");

        jLabel6.setText("JUMLAH :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_kodegudang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btn_getcode))
                    .addComponent(txt_namagudang)
                    .addComponent(txt_namaobat)
                    .addComponent(txt_jumlahstok))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_kodegudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_getcode))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_namagudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_namaobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_jumlahstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        tabel_gudang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabel_gudang);

        cbo_gudang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-PILIH-" }));
        cbo_gudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_gudangActionPerformed(evt);
            }
        });

        btn_carigudang.setText("CARI GUDANG");
        btn_carigudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carigudangActionPerformed(evt);
            }
        });

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel3.add(btn_simpan);

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_update);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete);

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel3.add(btn_reset);

        jLabel4.setText("Cari Obat :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbo_gudang, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_carigudang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addGap(34, 34, 34)
                                    .addComponent(txt_cariobat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_gudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_carigudang)
                    .addComponent(txt_cariobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
       if (validasiInput()==true){
           String kode = txt_kodegudang.getText();
           String namagudang = txt_namagudang.getText();
           String Namaobat = txt_namaobat.getText();
           int jumlahstok = Integer.valueOf(txt_jumlahstok.getText());
           
           GudangModel gm = new GudangModel();
           gm.setGudangkd(kode);
           gm.setNamaGudang(namagudang);
           gm.setNamaObat(Namaobat);
           gm.setStokobat(jumlahstok);
           
           gudangDao.insertGudang(gm);
           tableModelGudang.insertGudang(gm);
           loadData();
           resetFrm();
           JOptionPane.showMessageDialog(null, "Data berhasil Disimpan");
           loadGudang();
           loadGudang();
       }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_getcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getcodeActionPerformed
String KodeGudang = gudangDao.setAutonumber();
txt_kodegudang.setText(KodeGudang);// TODO add your handling code here:
    }//GEN-LAST:event_btn_getcodeActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
resetFrm();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
List<GudangModel> cekgudang = tableModelGudang.getGudangCek();
if (!cekgudang.isEmpty()){
if (JOptionPane.showConfirmDialog(null,"Konfirmasi", "Apakah anda ingin menghapus data ini ?",
        JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
    boolean valid = true;
    for (GudangModel g : cekgudang){
        if (valid){
            gudangDao.deleteGudang(g);
            loadData();
            loadGudang();
        }
    }
    JOptionPane.showMessageDialog(null, "Data Berhasil DIhapus");
    loadData();
    loadGudang();
    
}
}
else {
    JOptionPane.showMessageDialog(null, "Seleksi Salah Satu Baris");
}
loadGudang();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_carigudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carigudangActionPerformed
      if(cbo_gudang.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Siilahkan pilih Gudang Obat");
        }else{
            
          GudangModel gm = (GudangModel) cbo_gudang.getSelectedItem();
          List<GudangModel> gudangModels = gudangDao.getgudangmodelid(gm);
            
            if(!gudangModels.isEmpty()){
                tableModelGudang.setData(gudangModels);
            }else{
                JOptionPane.showMessageDialog(null, "Data Gudang tidak ditemukan");
            }
        }
        
    }//GEN-LAST:event_btn_carigudangActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
      int index = tabel_gudang.getSelectedRow();
      if (index!=-1){
          GudangModel g =  tableModelGudang.getGudangModel(tabel_gudang.convertRowIndexToModel(index));
          Dialog_update_gudang d = new Dialog_update_gudang();
          GudangModel update = d.updateGudang(g);
          if (update!=null){
              gudangDao.updateGudang(update);
              tableModelGudang.updateGudang(index, update);
          }
      }else {
          JOptionPane.showMessageDialog(null, "Seleksi Salah Satu Baris");
      }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void cbo_gudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_gudangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_gudangActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_carigudang;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_getcode;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox cbo_gudang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_gudang;
    private javax.swing.JTextField txt_cariobat;
    private javax.swing.JTextField txt_jumlahstok;
    private javax.swing.JTextField txt_kodegudang;
    private javax.swing.JTextField txt_namagudang;
    private javax.swing.JTextField txt_namaobat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
    Saring();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
    Saring();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
    Saring();
    }
}
