/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.frm;

import com.ridwan.DAO.KategoriDao;
import com.ridwan.TableModel.TableModelKategori;
import com.ridwan.dialog.Dialog_Update_Kategori;
import com.ridwan.model.KategoriModel;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ciwong
 */
public class KategoriFrm extends javax.swing.JFrame implements DocumentListener{
private KategoriDao kategoriDao = new KategoriDao();
private TableModelKategori tableModelKategori = new TableModelKategori();
private KategoriModel km;
private TableRowSorter rowSorter;
    /**
     * Creates new form KategoriFrm
     */
    public KategoriFrm() {
        initComponents();
        setLocationRelativeTo(null);
        table_kategori.setModel(tableModelKategori);
        loadData();
    rowSorter = new TableRowSorter(table_kategori.getModel());
       table_kategori.setRowSorter(rowSorter);
      txt_carikategori.getDocument().addDocumentListener(this);
    }
    
    
    private void Saring(){
        String text = txt_carikategori.getText();
        if (text.length()==0){
            rowSorter.setRowFilter(null);
        }else {
           rowSorter.setRowFilter(RowFilter.regexFilter
        (Pattern.compile("(?i).*" + text + ".*", Pattern.CASE_INSENSITIVE|Pattern.DOTALL ).toString()));
        }
    }
    
    private void loadData(){
    List<KategoriModel> kategoriModels = kategoriDao.getKategoriModels();
    tableModelKategori.setData(kategoriModels);
    }
    
    
    private void resetFrm(){
        txt_idkategori.setText("");
        txt_Namakategori.setText("");
    }
    
    private boolean validasiInput(){
        boolean valid = false;
        if (txt_idkategori.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Id Kategori Tidak Boleh Kosong");
        }else if (txt_Namakategori.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Kategori Tidak boleh Kosong");
        }else {
            valid = true;
        }
        return valid;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_idkategori = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Namakategori = new javax.swing.JTextField();
        btn_getcodekategori = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_kategori = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_smpan = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_carikategori = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORM INPUT KATEGORI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Id Kategori :");

        txt_idkategori.setEnabled(false);

        jLabel3.setText("Nama Kategori :");

        btn_getcodekategori.setText("Get");
        btn_getcodekategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getcodekategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_Namakategori))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txt_idkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_getcodekategori)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_idkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_getcodekategori))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Namakategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        table_kategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_kategori);

        btn_smpan.setText("SIMPAN");
        btn_smpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_smpanActionPerformed(evt);
            }
        });
        jPanel3.add(btn_smpan);

        btn_update.setText("EDIT");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_update);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete);

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel3.add(btn_reset);

        jLabel4.setText("CARI KATEGORI :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txt_carikategori, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_carikategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
int index = table_kategori.getSelectedRow();
if (index!=-1){
    KategoriModel k = tableModelKategori.getKategoriModel(table_kategori.convertRowIndexToModel(index));
    Dialog_Update_Kategori dialog_Update_Kategori = new Dialog_Update_Kategori();
    KategoriModel update = dialog_Update_Kategori.updateKategori(k);
    if (update!=null){
        kategoriDao.updateKategori(update);
        tableModelKategori.updateKategori(index, update);
    }
}else {
    JOptionPane.showMessageDialog(null, "Seleksi Salah Satu Baris");
}

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_getcodekategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getcodekategoriActionPerformed
String setAutoNumber = kategoriDao.setAutoNumber();
txt_idkategori.setText(setAutoNumber);// TODO add your handling code here:
    }//GEN-LAST:event_btn_getcodekategoriActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        List<KategoriModel> CekKategori = tableModelKategori.getKategoriCek();
if (!CekKategori.isEmpty()){
    if (JOptionPane.showConfirmDialog(null, "Konfirmasi", "Apakah Anda ingin menghapus Data ini ?", 
            JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
        boolean valid = true;
        for (KategoriModel kategoriModel : CekKategori){
            if (valid){
                kategoriDao.deleteKategori(kategoriModel);
            }
             loadData() ;
    resetFrm();
        }
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
       
    }
   
    
}else {
    JOptionPane.showMessageDialog(null,"Seleksi salah satu Baris");
}
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_smpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_smpanActionPerformed

if (validasiInput()==true){
String kode = txt_idkategori.getText();
String namakate = txt_Namakategori.getText();

KategoriModel k = new KategoriModel();
k.setKategoriKd(kode);
k.setNamaKategori(namakate);

kategoriDao.insertKategori(k);
tableModelKategori.insertKategori(k);
loadData();
resetFrm();

JOptionPane.showMessageDialog(null,"Data berhasil disimpan");
}else {
    JOptionPane.showMessageDialog(null, "Data gagal disimpan");
}

    }//GEN-LAST:event_btn_smpanActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
resetFrm();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_getcodekategori;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_smpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_kategori;
    private javax.swing.JTextField txt_Namakategori;
    private javax.swing.JTextField txt_carikategori;
    private javax.swing.JTextField txt_idkategori;
    // End of variables declaration//GEN-END:variables

    @Override
    
    public void insertUpdate(DocumentEvent e) {
    Saring();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
    Saring();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
    Saring();
    }
}
