/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.frm;

import com.ridwan.DAO.GudangDao;
import com.ridwan.DAO.KategoriDao;
import com.ridwan.DAO.ObatDao;
import com.ridwan.DAO.PetugasDao;
import com.ridwan.DAO.TransaksiDao;
import com.ridwan.dialog.TampilReport;
import com.ridwan.dialog.Trx_Bytgl;
import com.ridwan.model.GudangModel;
import com.ridwan.model.KategoriModel;
import com.ridwan.model.ObatModel;
import com.ridwan.model.PetugasModel;
import com.ridwan.model.ReportTransaksi;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ciwong
 */
public class LaporanFrm extends javax.swing.JFrame {

    /**
     * Creates new form LaporanFrm
     */
    public LaporanFrm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_lapgudang = new javax.swing.JButton();
        btn_lapkaryawan = new javax.swing.JButton();
        btn_lapgudang1 = new javax.swing.JButton();
        btn_lapgudang2 = new javax.swing.JButton();
        btn_lapgudang3 = new javax.swing.JButton();
        btn_lapgudang4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_lapgudang.setText("LAPORAN DATA OBAT");
        btn_lapgudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapgudangActionPerformed(evt);
            }
        });

        btn_lapkaryawan.setText("LAPORAN KARYAWAN");
        btn_lapkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapkaryawanActionPerformed(evt);
            }
        });

        btn_lapgudang1.setText("LAPORAN GUDANG");
        btn_lapgudang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapgudang1ActionPerformed(evt);
            }
        });

        btn_lapgudang2.setText("LAPORAN DATA KATEGORI");
        btn_lapgudang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapgudang2ActionPerformed(evt);
            }
        });

        btn_lapgudang3.setText("LAPORAN TRANSAKSI");
        btn_lapgudang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapgudang3ActionPerformed(evt);
            }
        });

        btn_lapgudang4.setText("LAPORAN TRANSAKSI BY TANGGAL");
        btn_lapgudang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapgudang4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_lapkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_lapgudang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_lapgudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_lapgudang2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                        .addComponent(btn_lapgudang3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                        .addComponent(btn_lapgudang4, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_lapgudang3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btn_lapkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_lapgudang1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_lapgudang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_lapgudang2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_lapgudang4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lapgudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapgudangActionPerformed
        ObatDao obatDao = new ObatDao();
        List<ObatModel> obatModels = obatDao.getObatModels();
        
        
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
        ("com/ridwan/Laporan/LaporanObat.jasper"), null, new JRBeanCollectionDataSource(obatModels));
            JRViewer jrv = new JRViewer(jasperPrint);
            TampilReport report = new TampilReport("Laporan Data Gudang", jrv);
        } catch (JRException jRException) {
            System.out.println(jRException.getMessage());
        }     
    }//GEN-LAST:event_btn_lapgudangActionPerformed

    private void btn_lapkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapkaryawanActionPerformed
      PetugasDao petugasDao = new PetugasDao();
        List<PetugasModel> petugasModels = petugasDao.petugasModels();
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
        ("com/ridwan/Laporan/LaporanKaryawan.jasper"), null, new JRBeanCollectionDataSource(petugasModels));
            JRViewer jrv = new JRViewer(jasperPrint);
            TampilReport report = new TampilReport("Laporan Semua Karyawan", jrv);
        } catch (JRException jRException) {
            System.out.println(jRException.getMessage());
        }
    }//GEN-LAST:event_btn_lapkaryawanActionPerformed

    private void btn_lapgudang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapgudang1ActionPerformed
    GudangDao gudangDao = new GudangDao();
        List<GudangModel> gudangModels = gudangDao.getgudangModels();
        
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
        ("com/ridwan/Laporan/LaporanGudang.jasper"), null, new JRBeanCollectionDataSource(gudangModels));
            JRViewer jrv = new JRViewer(jasperPrint);
            TampilReport report = new TampilReport("Laporan Data Gudang", jrv);
        } catch (JRException jRException) {
            System.out.println(jRException.getMessage());
        }
    }//GEN-LAST:event_btn_lapgudang1ActionPerformed

    private void btn_lapgudang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapgudang2ActionPerformed
        KategoriDao kategoriDao = new KategoriDao();
        List<KategoriModel> kategoriModels = kategoriDao.getKategoriModels();
        
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
        ("com/ridwan/Laporan/LaporanKategori.jasper"), null, new JRBeanCollectionDataSource(kategoriModels));
            JRViewer jrv = new JRViewer(jasperPrint);
            TampilReport report = new TampilReport("Laporan Data Gudang", jrv);
        } catch (JRException jRException) {
            System.out.println(jRException.getMessage());
        }
    }//GEN-LAST:event_btn_lapgudang2ActionPerformed

    private void btn_lapgudang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapgudang3ActionPerformed
  try {
        TransaksiDao transaksiDao = new TransaksiDao();
          List<ReportTransaksi> reportTransaksis = transaksiDao.getReportTransaksis();
        //HashMap map = new HashMap();
        //map.put("Semua Transaksi", "subTitle");
            JasperPrint jasperPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
        ("com/ridwan/Laporan/LaporanTransaksi.jasper"),
                    null, new JRBeanCollectionDataSource(reportTransaksis));
            JRViewer jrv = new JRViewer(jasperPrint);
            TampilReport report = new TampilReport("LAPORAN TRANSAKSI", jrv);
        } catch (JRException jRException) {
            System.out.println(jRException.getMessage());
        }                    // TODO add your handling code here:
    }//GEN-LAST:event_btn_lapgudang3ActionPerformed

    private void btn_lapgudang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapgudang4ActionPerformed
Trx_Bytgl bytgl = new Trx_Bytgl();
bytgl.setVisible(true);
    }//GEN-LAST:event_btn_lapgudang4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lapgudang;
    private javax.swing.JButton btn_lapgudang1;
    private javax.swing.JButton btn_lapgudang2;
    private javax.swing.JButton btn_lapgudang3;
    private javax.swing.JButton btn_lapgudang4;
    private javax.swing.JButton btn_lapkaryawan;
    // End of variables declaration//GEN-END:variables
}
