/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.frm;

import com.ridwan.DAO.KategoriDao;
import com.ridwan.DAO.ObatDao;
import com.ridwan.TableModel.TableModelKategori;
import com.ridwan.TableModel.TableModelObat;
import com.ridwan.dialog.Dialog_update_Obat;
import com.ridwan.dialog.Kategori_dialog;
import com.ridwan.model.KategoriModel;
import com.ridwan.model.ObatModel;
import java.util.Date;
import java.util.List;
import javafx.scene.control.ProgressBar;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;

/**
 *
 * @author ciwong
 */
public class OBATFRM extends javax.swing.JFrame {
    private ObatDao obatDao = new ObatDao();
   private TableModelObat tableModelObat = new TableModelObat();
   private ObatModel om;
   private TableModelKategori tableModelKategori = new TableModelKategori();
   private KategoriModel k;
   private KategoriDao kategoriDao = new KategoriDao();

    /**
     * Creates new form OBATFRM
     */
    public OBATFRM() {
        initComponents();
        setLocationRelativeTo(null);
        table_obat.setModel(tableModelObat);
        loadData();
        loadKategori();
        ProgressBar.setVisible(false);
        txt_label.setVisible(false);
    }
    
    private void loadData(){
        List<ObatModel> obatModels = obatDao.getObatModels();
        tableModelObat.setData(obatModels);
    }
    
    private void loadKategori(){
        List<KategoriModel> kategoriModels = kategoriDao.getKategoriModels();
        for (KategoriModel k1 : kategoriModels){
            cbo_kategori.addItem(k1);
        }
    }
    
    
    private void isiKategori(KategoriModel kategoriModel){
       txt_kdkategori.setText(kategoriModel.getKategoriKd());
        txt_namakategori.setText(kategoriModel.getNamaKategori());
        
    }
    
    private boolean validasiInput(){
        boolean valid = false;
        if (txt_kodeobat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode Obat Tidak Boleh Kosong");
        }else if (txt_namaobat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Obat Tidak Boleh Kosong");
        }else if (txt_jumlahobat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah Obat Tidak BOleh Kosong");
        }else if (txt_kdkategori.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Kode Kategori Tidak Boleh Kosong");
        }else if (txt_namakategori.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Kategori Tidak Boleh Kosong");
        }else if (txt_tglKadaluarsa.getDate()==null){
            JOptionPane.showMessageDialog(null, "Tanggal Kadaluarsa Masih Kosong");
        }else if (txt_harga.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga Tidak Boleh Kosong");
        }else {
            valid = true;
        }
        return valid;
    }
    
    private void resetFrm(){
        txt_kodeobat.setText("");
        txt_namaobat.setText("");
        txt_jumlahobat.setText("");
        txt_kdkategori.setText("");
        txt_namakategori.setText("");
        txt_tglKadaluarsa.setDate(null);
        txt_harga.setText("");
        cbo_kategori.setSelectedIndex(0);
    }

    
    class tampilWorker extends SwingWorker{

        @Override
        protected Object doInBackground() throws Exception {
        for (int i=0; i<=150 ; i++){
            Thread.sleep(15);
            ProgressBar.setValue(i);
            ProgressBar.setVisible(true);
            txt_label.setVisible(true);
           ProgressBar.setIndeterminate(true);
           
        }
            return null;
        }
        
        @Override
        protected void done (){
            ProgressBar.setVisible(false);
            txt_label.setVisible(false);
            
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_kodeobat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_namaobat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_jumlahobat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_kdkategori = new javax.swing.JTextField();
        txt_namakategori = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        btn_ambilkode = new javax.swing.JButton();
        btn_pilihktgori = new javax.swing.JButton();
        txt_tglKadaluarsa = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_obat = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cbo_kategori = new javax.swing.JComboBox();
        btn_cari = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_simpan = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();
        txt_label = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORM DATA OBAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Kode Obat :");

        txt_kodeobat.setEnabled(false);

        jLabel3.setText("Nama Obat :");

        jLabel4.setText("Jumlah :");

        jLabel5.setText("Kategori :");

        txt_kdkategori.setEnabled(false);

        txt_namakategori.setEnabled(false);
        txt_namakategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namakategoriActionPerformed(evt);
            }
        });

        jLabel6.setText("Tgl Kadaluarsa :");

        jLabel7.setText("Harga :");

        btn_ambilkode.setText("Get Code");
        btn_ambilkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ambilkodeActionPerformed(evt);
            }
        });

        btn_pilihktgori.setText("Pilih");
        btn_pilihktgori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihktgoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_namaobat)
                    .addComponent(txt_jumlahobat)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_kdkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_namakategori, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addComponent(txt_harga)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_kodeobat, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ambilkode))
                    .addComponent(txt_tglKadaluarsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_pilihktgori, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_kodeobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_ambilkode)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txt_namaobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_jumlahobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_kdkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namakategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pilihktgori))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_tglKadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        table_obat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_obat);

        jLabel8.setText("CARI :");

        cbo_kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "_CARI_" }));
        cbo_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_kategoriActionPerformed(evt);
            }
        });

        btn_cari.setText("Cari Obat");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel4.add(btn_simpan);

        btn_update.setText("EDIT");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel4.add(btn_update);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel4.add(btn_delete);

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel4.add(btn_reset);

        txt_label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_label.setText("Please Waittt....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(txt_label))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cari)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbo_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addGap(2, 2, 2)
                .addComponent(txt_label)
                .addGap(10, 10, 10)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namakategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namakategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namakategoriActionPerformed

    private void btn_ambilkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ambilkodeActionPerformed
String setAutonumber = obatDao.setAutoNumber();
txt_kodeobat.setText(setAutonumber);// TODO add your handling code here:
    }//GEN-LAST:event_btn_ambilkodeActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
if (validasiInput()==true){
        tampilWorker worker = new tampilWorker();
String Kodeobat = txt_kodeobat.getText();
String namaobat = txt_namaobat.getText();
int jumlah = Integer.valueOf(txt_jumlahobat.getText());
String namakategori = txt_namakategori.getText();
String kdkategori = txt_kdkategori.getText();
        Date tglkadaluarsa = txt_tglKadaluarsa.getDate();
        Double harga = Double.valueOf(txt_harga.getText());
        
        
        ObatModel om = new ObatModel();
        KategoriModel km = new KategoriModel();
        om.setObatKd(Kodeobat);
        om.setNamaObat(namaobat);
        om.setJumlah(jumlah);
        km.setKategoriKd(kdkategori);
        om.setKategori(km);
        om.setTglKadaluarsa(tglkadaluarsa);
        om.setHarga(harga);
        
        obatDao.insertObat(om);
        tableModelObat.insertObat(om);
        worker.execute();
        loadData();
        resetFrm();
        JOptionPane.showMessageDialog(null, "Data berhasil Disimpan");
}

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_pilihktgoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihktgoriActionPerformed
 Kategori_dialog dialog=new Kategori_dialog();
        k=dialog.ambilKategori();
        if(k!=null){
            isiKategori(k);
}
        
    }//GEN-LAST:event_btn_pilihktgoriActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
resetFrm();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    List<ObatModel> CekObat = tableModelObat.getObatCek();
    if (!CekObat.isEmpty()){
        if (JOptionPane.showConfirmDialog(null, "Konfirmasi", "Apakah anda Ingin Menghapus data ini", 
                JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
            boolean valid = true;
            for (ObatModel om : CekObat){
                if (valid){
                    obatDao.deleteObat(om);
                }
            }
            JOptionPane.showMessageDialog(null,"Data berhasil Dihapus");
        loadData();
        }
        
    }else {
        JOptionPane.showMessageDialog(null, "Seleksi Salah Satu baris");
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
      int index = table_obat.getSelectedRow();
      if (index!=-1){
          ObatModel om = tableModelObat.getobatModel(table_obat.convertRowIndexToModel(index));
          Dialog_update_Obat dialog_update_Obat = new Dialog_update_Obat();
          ObatModel update = dialog_update_Obat.updateObat(om);
          if (update!=null){
              obatDao.updateObat(update);
              tableModelObat.updateObat(index, update);
          }
      }
      else {
          JOptionPane.showMessageDialog(null, "Seleksi Salah Satu Baris");
      }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
      if(cbo_kategori.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Siilahkan piliih kategorii Obat");
        }else{
            
            KategoriModel k1= (KategoriModel) cbo_kategori.getSelectedItem();
          List<ObatModel> kategoriModels = obatDao.getKategoriModels(k1);
            
            if(!kategoriModels.isEmpty()){
                tableModelObat.setData(kategoriModels);
            }else{
                JOptionPane.showMessageDialog(null, "Data Kategori tidak ditemukan");
            }
        }
        
    }//GEN-LAST:event_btn_cariActionPerformed

    private void cbo_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_kategoriActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton btn_ambilkode;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_pilihktgori;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox cbo_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_obat;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlahobat;
    private javax.swing.JTextField txt_kdkategori;
    private javax.swing.JTextField txt_kodeobat;
    private javax.swing.JLabel txt_label;
    private javax.swing.JTextField txt_namakategori;
    private javax.swing.JTextField txt_namaobat;
    private com.toedter.calendar.JDateChooser txt_tglKadaluarsa;
    // End of variables declaration//GEN-END:variables
}
