/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.frm;

import com.ridwan.DAO.ObatDao;
import com.ridwan.DAO.PetugasDao;
import com.ridwan.DAO.TransaksiDao;
import com.ridwan.Interface.TransaksiInterface;
import com.ridwan.Main.MAIN_MENU;
import com.ridwan.TableModel.TableModelTransaksiDetail;
import com.ridwan.dialog.Ambilobatdialog;
import com.ridwan.dialog.TampilReport;
import com.ridwan.model.ObatModel;
import com.ridwan.model.PetugasModel;
import com.ridwan.model.ReportTransaksi;
import com.ridwan.model.Transaksi;
import com.ridwan.model.TransaksiDetail;
import com.sun.java.swing.plaf.motif.resources.motif_zh_TW;
import com.sun.swing.internal.plaf.metal.resources.metal;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ciwong
 */
public class TransaksiFrm extends javax.swing.JFrame {
    
    private TableModelTransaksiDetail tableModelTransaksiDetail = new TableModelTransaksiDetail();
    private TransaksiDao transaksiDao = new TransaksiDao();
    private Transaksi transaksi;
    private ObatModel obatModel;
    List<Transaksi> list = new ArrayList<>();
    private Date tanggal = new Date();
    private PetugasModel p;
    private PetugasDao petugasDao = new PetugasDao();
    private boolean modeEdit;
    
    

    
    
   
    /**
     * Creates new form TransaksiFrm
     */
    public TransaksiFrm() {
        initComponents();
        setLocationRelativeTo(null);
        tabel_trx.setModel(tableModelTransaksiDetail);
        txt_tgltrx.setDate(tanggal);
      loadPetugas();
    }
    
    
    
    private void resetFrm(){
        txt_kodetrx.setText("");
       txt_total.setText("");
       tableModelTransaksiDetail.clear();
       cbo_petugas.setSelectedIndex(0);
    }
    
    private void loadPetugas(){
        List<PetugasModel> petugasModels = petugasDao.petugasModels();
        for (PetugasModel p : petugasModels){
            cbo_petugas.addItem(p);
        }
    }
    
    
    
    
    
    private boolean validasiInput(){
        boolean valid = false;
        if (txt_kodetrx.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Transaksi Kode Belum Ada");
        }else if (txt_tgltrx.getDate()==null){
            JOptionPane.showMessageDialog(null, "Tanggal Transkasi belum ada");
        }else if(tabel_trx.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "obat belum dipilih!");
        }else if (cbo_petugas.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "petugas belum dipilih");
        } else if (txt_total.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "TOTAL BELUM ADA");
        }
        else {
           valid = true;
        }
        return valid;
    }
    
    
    private int validasiHitung(){
        int jumlah = 0;
        for (int i=0; i<tableModelTransaksiDetail.getRowCount(); i++){
            jumlah = (int) tabel_trx.getValueAt(i, 1);
        }
        return jumlah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_kodetrx = new javax.swing.JTextField();
        txt_tgltrx = new com.toedter.calendar.JDateChooser();
        btn_getcode = new javax.swing.JButton();
        btn_ambilobat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbo_petugas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_trx = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        btn_hitungtotal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("TRANSAKSI FORM");
        jPanel1.add(jLabel1);

        jLabel2.setText("KODE TRANSAKSI :");

        jLabel3.setText("TANGGAL :");

        txt_kodetrx.setEnabled(false);

        txt_tgltrx.setEnabled(false);

        btn_getcode.setText("GET");
        btn_getcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getcodeActionPerformed(evt);
            }
        });

        btn_ambilobat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_ambilobat.setText("PILIH OBAT");
        btn_ambilobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ambilobatActionPerformed(evt);
            }
        });

        jLabel4.setText("PETUGAS :");

        cbo_petugas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-PILIH-" }));
        cbo_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_petugasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ambilobat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_kodetrx)
                    .addComponent(txt_tgltrx, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(cbo_petugas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(btn_getcode)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_kodetrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_getcode))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_tgltrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbo_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btn_ambilobat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabel_trx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabel_trx);

        jLabel5.setText("TOTAL :");

        txt_total.setEnabled(false);

        btn_hitungtotal.setText("HITUNG");
        btn_hitungtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungtotalActionPerformed(evt);
            }
        });

        jButton1.setText("SIMPAN & CETAK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 22, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hitungtotal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hitungtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_getcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getcodeActionPerformed
String kodeTRX = transaksiDao.KodeTransaksi();
txt_kodetrx.setText(kodeTRX);// TODO add your handling code here:
    }//GEN-LAST:event_btn_getcodeActionPerformed

    private void btn_hitungtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungtotalActionPerformed
    int jumlahbaris = tabel_trx.getRowCount();
    double total_biaya = 0;
    double jumlahBarang, hargaBarang;
        TableModel tableModel;
        tableModel = tabel_trx.getModel();
        if (validasiHitung()==0){
            JOptionPane.showMessageDialog(null, "Masih ada barang yang Jumlahnya 0");
        }else {
            for (int i=0; i<jumlahbaris; i++){
               jumlahBarang = Double.parseDouble(tableModel.getValueAt(i, 1).toString());
               hargaBarang = Double.parseDouble(tableModel.getValueAt(i, 2).toString());
               total_biaya =total_biaya + (jumlahBarang*hargaBarang);
            }
            txt_total.setText(String.valueOf(total_biaya));
        }
    }//GEN-LAST:event_btn_hitungtotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
resetFrm();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (validasiInput()==true){
        transaksi = new Transaksi();
        transaksi.setTransaksikd(String.valueOf(txt_kodetrx.getText()));
        transaksi.setTglTransaksi(txt_tgltrx.getDate());
      transaksi.setPetugas((PetugasModel) cbo_petugas.getSelectedItem());
        
        List<TransaksiDetail> transaksiDetils = new ArrayList<>();
        for (int i=0; i<tabel_trx.getRowCount();  i++){
            TransaksiDetail detil = new TransaksiDetail();
            detil.setTransaksi(transaksi);
            
            ObatModel om = (ObatModel) tabel_trx.getValueAt(i, 0);
            int jumlah = (int) tabel_trx.getValueAt(i, 1);
            Double harga = (Double) tabel_trx.getValueAt(i, 2);
            
            detil.setHarga(harga);
            detil.setJumlah(jumlah);
            detil.setObat(om);
            transaksiDetils.add(detil);
        }
        
        transaksi.setGettrTransaksiDetils(transaksiDetils);
        if (transaksiDao.InsertTransaksi(transaksi)==true){
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            list.add(transaksi);
            resetFrm();
            try {
            TransaksiInterface dao = new TransaksiDao();
            List<ReportTransaksi> transaksi1 = dao.getTransaksi(transaksi);
            HashMap map = new HashMap();
            map.put("SubTitle", "Berdasarkan ID Transaksi"+transaksi.getTransaksikd());
            JasperPrint jp = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/ridwan/Laporan/LaporanTransaksi.jasper"), map, new JRBeanCollectionDataSource(transaksi1));
            JRViewer jrv = new JRViewer(jp);
            TampilReport report = new TampilReport("Laporan Transaksi berdasarkan Id", jrv);
        } catch (JRException ex) {
            Logger.getLogger(TransaksiFrm.class.getName()).log(Level.SEVERE, null, ex);
        }      
            
        }else {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_ambilobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ambilobatActionPerformed
     boolean valid = false;
        Ambilobatdialog ambilobatdialog = new Ambilobatdialog();
        obatModel = ambilobatdialog.ambilObat();
        if (obatModel!=null){
            List<ObatModel> obatcek = ambilobatdialog.tableModelObat.getObatCek();
            for (ObatModel om : obatcek){
                TransaksiDetail detil = new TransaksiDetail();
                detil.setObat(om);
                detil.setJumlah(0);
                detil.setHarga(om.getHarga());
                
                for (int i=0 ; i<tabel_trx.getRowCount(); i++){
                    TransaksiDetail td = tableModelTransaksiDetail.getTransaksiDetail(i);
                    if (td.getObat().getNamaObat().equals(detil.getObat().getNamaObat())){
                        valid = true;
                    }
                }
                if (valid==false){
                    tableModelTransaksiDetail.insertTransaksiDetail(detil);
                }else {
                    JOptionPane.showMessageDialog(null, "MAaf Nama Barang Sudah ada");
                }
            }
        }
        
    }//GEN-LAST:event_btn_ambilobatActionPerformed

    private void cbo_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_petugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_petugasActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ambilobat;
    private javax.swing.JButton btn_getcode;
    private javax.swing.JButton btn_hitungtotal;
    private javax.swing.JComboBox cbo_petugas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_trx;
    private javax.swing.JTextField txt_kodetrx;
    private com.toedter.calendar.JDateChooser txt_tgltrx;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
