/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.dialog;

import com.ridwan.model.ObatModel;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ciwong
 */
public class Dialog_update_Obat extends javax.swing.JDialog {
    
    private ObatModel obatModel;
    private boolean modeedit;

    /**
     * Creates new form Dialog_update_Obat
     */
    public Dialog_update_Obat() {
        setModal(true);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public ObatModel updateObat(ObatModel o){
        this.modeedit=true;
        this.obatModel=o;
        txt_namaobat.setText(o.getNamaObat());
        txt_jumlah.setText(String.valueOf(o.getJumlah()));
        txt_tglkadaluarsa.setDate(o.getTglKadaluarsa());
        txt_harga.setText(String.valueOf(o.getHarga()));
        setLocationRelativeTo(getParent());
        setVisible(true);
        return obatModel;
    }
    
    
    private void resetfrm(){
        txt_namaobat.setText("");
        txt_jumlah.setText("");
        txt_tglkadaluarsa.setDate(null);
        txt_harga.setText("");
    }
    
    
    private boolean validasiinput(){
        boolean valid = false;
        if (txt_namaobat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Obat harus diisi");
            
        }else if (txt_jumlah.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah harus terisi");
        }else if (txt_tglkadaluarsa.getDate()==null){
            JOptionPane.showMessageDialog(null, "Tanggal Kadaluarsa Harus diisi");
        }else if (txt_harga.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"arga Harus diisi");
        }else {
            valid = true;
        }
        return valid;
    }
            
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_namaobat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        txt_tglkadaluarsa = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama Obat :");

        jLabel2.setText("Jumlah :");

        jLabel3.setText("Tgl Kadaluarsa :");

        jLabel4.setText("Harga :");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_jumlah)
                        .addComponent(txt_tglkadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_namaobat)
                        .addComponent(txt_harga, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_namaobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txt_tglkadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_batal))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
   if  (validasiinput()==true){
       String nama = txt_namaobat.getText();
       int Jumlah = Integer.valueOf(txt_jumlah.getText());
       Date tgl = txt_tglkadaluarsa.getDate();
       Double harga = Double.valueOf(txt_harga.getText());
       
       obatModel.setNamaObat(nama);
       
       obatModel.setJumlah(Jumlah);
       obatModel.setTglKadaluarsa(tgl);
       obatModel.setHarga(harga);
       
       JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
       resetfrm();
       dispose();
   }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_namaobat;
    private com.toedter.calendar.JDateChooser txt_tglkadaluarsa;
    // End of variables declaration//GEN-END:variables
}
