/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.dialog;

import com.ridwan.DAO.GudangDao;
import com.ridwan.TableModel.TableModelGudang;
import com.ridwan.model.GudangModel;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ciwong
 */
public class info_gudang extends javax.swing.JDialog implements DocumentListener{
    
private TableModelGudang tableModelGudang = new TableModelGudang();
private GudangModel g;
private GudangDao gudangDao = new GudangDao();
private TableRowSorter rowSorter;
    /**
     * Creates new form info_gudang
     */
    public info_gudang() {
        setModal(true);
        initComponents();
        setLocationRelativeTo(null);
        loadData();
        tabel_infogudang.setModel(tableModelGudang);
        rowSorter = new TableRowSorter(tabel_infogudang.getModel());
        tabel_infogudang.setRowSorter(rowSorter);
        txt_cari.getDocument().addDocumentListener(this);
    }
    
    
    
    private void Saring(){
        String text =txt_cari.getText();
        if (text.length()==0){
            rowSorter.setRowFilter(null);
        }else {
            rowSorter.setRowFilter(RowFilter.regexFilter
        (Pattern.compile("(?i).*"+ text + ".*", Pattern.CASE_INSENSITIVE|Pattern.DOTALL).toString()));
        }
    }
    
    private void loadData(){
    List<GudangModel> gudangModels = gudangDao.getgudangModels();
    tableModelGudang.setData(gudangModels);
    }
    
    private GudangModel ambilGudang(){
        setVisible(true);
        setLocationRelativeTo(getParent());
        return g;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_infogudang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabel_infogudang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabel_infogudang);

        jLabel1.setText("CARI :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_infogudang;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
    Saring();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
    Saring();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
    Saring();
    }
}
